Update setup.py
fix compatibility, python3.x:
 print "Setting up sympa"
                        ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Setting up sympa")?